baseURL = 'https://demerzelsun12.github.io/'
# languageCode = 'en-us'
title = "Demerzel's Blog"
theme = "reimu"

# language mode
languageCode = 'zh-CN'
defaultContentLanguage = 'zh-CN'
[languages]
[languages.zh-CN]
languageName = '简体中文'
weight = 1
hasCJKLanguage = true


# code mode
[markup.highlight]
guessSyntax = true
noClasses = false

# search mode
[outputs]
home = ["Algolia", "HTML", "RSS"]

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

# math mode
[markup.goldmark.extensions.passthrough]
enable = true
delimiters.block = [["\\[", "\\]"], ["$$", "$$"]]
delimiters.inline = [["\\(", "\\)"], ["$", "$"]]




